# Generated by Django 5.1.4 on 2025-01-06 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0002_remove_category_created_at_and_more"),
        ("city", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                (
                    "floor",
                    models.CharField(
                        choices=[
                            ("Ground", "Ground"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                        ],
                        max_length=50,
                    ),
                ),
                ("landmark", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("area", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "facilities",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("24h_water", "24 Hours Water"),
                            ("cold_water", "Cold Water"),
                            ("hot_water", "Hot Water"),
                            ("separate_bathroom", "Separate Bathroom"),
                            ("common_bathroom", "Common Bathroom"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "allowable_in_room",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                        ],
                        default="1",
                        max_length=2,
                    ),
                ),
                (
                    "light_responsibility",
                    models.CharField(
                        choices=[("Owner", "Owner"), ("Renter", "Renter")],
                        default="Owner",
                        max_length=20,
                    ),
                ),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                (
                    "image5",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="city.city"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
